import pandas as pd
import numpy as np

class ProductAnalyst:
    def __init__(self, data_frame: pd.DataFrame):
        """
        Initializes the ProductAnalyst.
        Focuses on product performance, stock health, and popularity metrics.
        """
        self.df = data_frame.copy()
        
        # חישוב הכנסה לשורה
        if 'Quantity' in self.df.columns and 'Price' in self.df.columns:
            self.df['Revenue'] = self.df['Quantity'] * self.df['Price']
            
        # וודוא עמודת תאריך לניתוחי מגמות
        if 'InvoiceDate' in self.df.columns:
            self.df['InvoiceDate'] = pd.to_datetime(self.df['InvoiceDate'], errors='coerce')



    def get_total_products_sold(self) -> dict:
        """Calculates the total quantity of units sold for each product."""
        return self.df.groupby('Description')['Quantity'].sum().to_dict()

    def get_product_revenue(self) -> dict:
        """Calculates the total revenue generated by each individual product."""
        return self.df.groupby('Description')['Revenue'].sum().to_dict()

    def get_average_price_per_product(self) -> dict:
        """Calculates the actual weighted average selling price for each product."""
        grouped = self.df.groupby('Description').agg({'Revenue': 'sum', 'Quantity': 'sum'})
        avg_price = grouped['Revenue'] / grouped['Quantity']
        return avg_price.to_dict()

    def get_product_sales_trend(self, product_desc: str) -> str:
        """Determines the sales trend (Up or Down percentage) for a specific product. Requires the exact product name as input."""
        if 'InvoiceDate' not in self.df.columns: return "No date data"
        prod_data = self.df[self.df['Description'] == product_desc].set_index('InvoiceDate')
        if prod_data.empty: return f"Product '{product_desc}' not found."
        monthly = prod_data['Quantity'].resample('ME').sum()
        if len(monthly) < 2: return "Not enough history"
        change = ((monthly.iloc[-1] - monthly.iloc[-2]) / monthly.iloc[-2]) * 100
        return f"{'Up' if change > 0 else 'Down'} ({change:.2f}%)"

    def get_top_products_by_revenue(self, limit: int = 10) -> dict:
        """Gets the top products ranked by total revenue generated. Allows specifying a limit (default 10)."""
        return self.df.groupby('Description')['Revenue'].sum().nlargest(limit).to_dict()

    def get_top_products_by_quantity(self, limit: int = 10) -> dict:
        """Gets the top products ranked by the total number of units sold. Allows specifying a limit (default 10)."""
        return self.df.groupby('Description')['Quantity'].sum().nlargest(limit).to_dict()

    def get_low_stock_indicator(self, threshold: int = 20) -> str:
        """Identifies products that might have low stock based on high sales volume."""
        return "Feature requires real-time inventory data."

    def get_product_conversion_rate(self) -> str:
        """Calculates the conversion rate per product (requires session data)."""
        return "Requires Session/Traffic data to calculate."

    def get_product_return_rate(self) -> dict:
        """Calculates the return rate percentage (refunds) for each product."""
        returns = self.df[self.df['Quantity'] < 0].groupby('Description')['Quantity'].sum().abs()
        sales = self.df[self.df['Quantity'] > 0].groupby('Description')['Quantity'].sum()
        rate = (returns / sales) * 100
        return rate.dropna().to_dict()

    def get_product_revenue_share(self) -> dict:
        """Calculates the percentage of total company revenue that each top product is responsible for."""
        total_rev = self.df['Revenue'].sum()
        share = (self.df.groupby('Description')['Revenue'].sum() / total_rev) * 100
        return share.nlargest(10).to_dict()

    def get_product_growth_rate(self, product_desc: str) -> str:
        """Calculates the exact growth rate for a specific product. Requires the exact product name as input."""
        return self.get_product_sales_trend(product_desc) 

    def get_product_popularity_score(self) -> dict:
        """Calculates a weighted popularity score for products based on quantity sold and unique invoices."""
        stats = self.df.groupby('Description').agg({'Quantity': 'sum', 'Invoice': 'nunique'})
        stats['Score'] = stats['Quantity'] * stats['Invoice']
        return stats['Score'].nlargest(10).to_dict()

    def get_product_profit_estimate(self) -> str:
        """Estimates the profit margin per product."""
        return "Requires Cost data (COGS) to calculate."

    def get_product_purchase_frequency(self) -> dict:
        """Calculates how often a product appears in orders (percentage of total orders)."""
        total_orders = self.df['Invoice'].nunique()
        freq = (self.df.groupby('Description')['Invoice'].nunique() / total_orders) * 100
        return freq.nlargest(10).to_dict()

    def get_product_lifecycle_status(self, product_desc: str) -> str:
        """Classifies a specific product's lifecycle status as Growing, Stable, or Declining. Requires the exact product name as input."""
        if 'InvoiceDate' not in self.df.columns: return "Unknown"
        prod_data = self.df[self.df['Description'] == product_desc].set_index('InvoiceDate')
        if prod_data.empty: return f"Product '{product_desc}' not found."
        monthly = prod_data['Quantity'].resample('ME').sum()
        if len(monthly) < 3: return "New Product"
        
        last_3_months = monthly.tail(3).values
        if last_3_months[2] > last_3_months[1] > last_3_months[0]: return "Growing"
        if last_3_months[2] < last_3_months[1] < last_3_months[0]: return "Declining"
        return "Stable"